include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

  plugins:
    - dart_code_linter

dart_code_linter:

  metrics:
    cyclomatic-complexity: 7
    maximum-nesting: 2

  metrics-exclude:
    - lib/navigations.dart

  rules-exclude:
    - lib/generated/**

  rules:
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - newline-before-return
    - no-empty-block


