// Mocks generated by Mockito 5.4.4 from annotations
// in highstyleapparel/test/login/bloc/login_bloc_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:highstyleapparel/login/contract.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginFlowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginFlowRepository extends _i1.Mock
    implements _i2.LoginFlowRepository {
  MockLoginFlowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic login(
    String? emailAddress,
    String? password,
  ) =>
      super.noSuchMethod(Invocation.method(
        #login,
        [
          emailAddress,
          password,
        ],
      ));

  @override
  dynamic signup(
    String? firstName,
    String? lastName,
    String? emailAddress,
    String? password,
    String? confirmPassword,
    String? mobileNumber,
  ) =>
      super.noSuchMethod(Invocation.method(
        #signup,
        [
          firstName,
          lastName,
          emailAddress,
          password,
          confirmPassword,
          mobileNumber,
        ],
      ));

  @override
  dynamic forgotPassword(String? emailAddress) =>
      super.noSuchMethod(Invocation.method(
        #forgotPassword,
        [emailAddress],
      ));

  @override
  dynamic createNewPassword(
    String? password,
    String? confirmPassword,
  ) =>
      super.noSuchMethod(Invocation.method(
        #createNewPassword,
        [
          password,
          confirmPassword,
        ],
      ));

  @override
  dynamic verifyCode(String? verifyCode) =>
      super.noSuchMethod(Invocation.method(
        #verifyCode,
        [verifyCode],
      ));
}
